name: Mirror to LI_L GitHub Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:lynnlangit/aws-cost-control.git'
          destination-repo: 'git@github.com:lynnlangit/aws-cost-control-copy.git'
